spring:
  datasource:
    initialization-mode: never
    url: jdbc:mysql://localhost:3306/zizser
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update  # create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      repositories:
        bootstrap-mode: default

logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG